# Generated by Selenium IDE; edited
import pytest

from selenium.webdriver.common.by import By

class TestAppTours:
    @pytest.mark.slow
    def test_navigate_in_app_menus(self, server, browser, reset_projects):
        """
        Test the navigation in the app menus
        """
        browser.get(f"{server}/projects/")

        # Navigate to app settings
        browser.find_element(By.LINK_TEXT, "Settings").click()
        assert browser.find_element(By.CSS_SELECTOR, "h1").text == "App settings"

        # Navigate back to projects
        browser.find_element(By.LINK_TEXT, "Projects").click()
        assert browser.find_element(By.CSS_SELECTOR, "h1").text == "ProjectHub"